<div x-data="initGtmToolbar()" @private-content-loaded.window="initToolbar()"></div>
<style>
    .mst-gtm__toolbar, .mst-gtm__toolbar-extra {
        outline: 5px solid rgba(74, 69, 66, 0.3);
        z-index: 1000000;
    }
    .mst-gtm__toolbar .mst-gtm__toolbar-body {
        max-height: 40rem;
    }
    .mst-gtm__toolbar-extra {
        left: 22rem;
    }
    .mst-gtm__toolbar-extra pre {
        width: 35rem;
        height: 25rem;
    }
</style>

<script>
    function initGtmToolbar() {
        return {
            cookieName: 'mst_gtm_debug',
            debugOn:    'gtm',

            wrapperClassList: 'mst-gtm__toolbar fixed left-4 bottom-4 card p-0 rounded-none text-sm w-80',
            titleClassList:   'btn btn-primary rounded-none text-center block font-semibold',
            bodyClassList:    'mst-gtm__toolbar-body overflow-y-auto',
            eventClassList:   'mst-gtm__toolbar-event card m-2 p-2 border-grey-200 border-2 relative cursor-pointer',
            idxClassList:     'bg-blue-600 px-2 py-1 mr-3 text-white font-normal',
            linkClassList:    'float-right text-gray-400 mr-2 underline',
            extraClassList:   'mst-gtm__toolbar-extra fixed bottom-4 card rounded-none text-xs',
            preClassList:     'overflow-auto p-2 whitespace-pre-wrap leading-5',

            initToolbar: function () {
                const currentUrl = new URL(window.location);

                if (currentUrl.searchParams.get('debug') === this.debugOn) {
                    if (hyva.getCookie(this.cookieName) === this.debugOn) {
                        hyva.setCookie(this.cookieName, '', 1);
                    } else {
                        hyva.setCookie(this.cookieName, this.debugOn, 1);
                    }
                }

                if (hyva.getCookie(this.cookieName) === this.debugOn) {
                    const elements = document.getElementsByClassName('mst-gtm__toolbar')
                    while(elements.length > 0){
                        elements[0].parentNode.removeChild(elements[0]);
                    }

                    document.body.appendChild(this.getWrapperHtml());

                    this.$toolbarBody = document.querySelector('.mst-gtm__toolbar-body');

                    let len = 0;
                    setInterval(function () {
                        if (window.dataLayer.length !== len) {
                            this.updateToolbar();

                            len = window.dataLayer.length
                        }
                    }.bind(this), 1000);
                }
            },

            updateToolbar: function () {
                this.$toolbarBody.innerHTML = '';

                let index = 1;

                window.dataLayer.forEach(function (data) {
                    if (typeof data.event != 'undefined') {
                        const $displayData = this.createToolbarElement('pre', false, this.preClassList);
                        const $code        = this.createToolbarElement('code', JSON.stringify(data, undefined, 4));

                        $displayData.appendChild($code);

                        const $event = this.createToolbarElement('div', false, this.eventClassList);

                        $event.appendChild(this.createToolbarElement('strong', '#' + index, this.idxClassList));
                        $event.appendChild(this.createToolbarElement('span', 'Event: ' + data.event));
                        $event.appendChild(this.createToolbarElement('span', 'Open', this.linkClassList));

                        $event.addEventListener('click', function () {
                            this.displayData($displayData)
                        }.bind(this));

                        this.$toolbarBody.appendChild($event);

                        index++
                    }
                }.bind(this));
            },

            getWrapperHtml: function () {
                const $wrapper = this.createToolbarElement('div', false, this.wrapperClassList);
                const $title   = this.createToolbarElement('strong', 'Google Tag Manager', this.titleClassList);
                const $body    = this.createToolbarElement('div', false, this.bodyClassList);

                $wrapper.appendChild($title);
                $wrapper.appendChild($body);

                return $wrapper;
            },

            displayData: function ($data) {
                const toolbarExtra = document.querySelector('body .mst-gtm__toolbar-extra');

                if (toolbarExtra) {
                    toolbarExtra.parentNode.removeChild(toolbarExtra);
                }

                const $t = this.createToolbarElement('div', false, this.extraClassList);
                $t.appendChild($data);

                document.body.appendChild($t);
            },

            createToolbarElement: function (tagName, data, classList) {
                const element = document.createElement(tagName);

                if (data) {
                    element.innerHTML = data;
                }

                if (classList) {
                    classList = classList.split(' ');
                    classList.forEach(function (classItem) {
                        element.classList.add(classItem);
                    });
                }

                return element;
            }
        }
    }
</script>
